#-------------------------------
# General Site Settings

title: Nakamoto's Blog
description: Nakamotoのブログです。RCJの事とか色々書いていく予定です。 # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nakamoto800.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name: Nakamoto
author-avatar: icon.jpg


#-------------------------------
# Contact links
twitter: https://twitter.com/Nakamoto_RCJ # Add your Facebook handle
github: https://github.com/nakamoto800


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jelyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Tokyo

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
